"""Generic MyMCP plugin contracts."""

from mymcp.plugin.composition import (
    ActivatedTool,
    ComposedToolSurface,
    HostToolOrigin,
    PluginContribution,
    compose_tool_surface,
)
from mymcp.plugin.contracts import (
    CapabilityKind,
    CapabilityLocalId,
    ConsentRequirement,
    PluginId,
    PluginVersion,
    PublicToolBinding,
    QualifiedCapabilityId,
    ToolEffects,
)
from mymcp.plugin.definition import (
    AuthorityDeclaration,
    CapabilityContractVersion,
    CapabilityDeclaration,
    ConfigurationDeclaration,
    ConfigurationSchema,
    ConfigurationSchemaVersion,
    ConfigurationType,
    FilesystemAuthority,
    HostApiRange,
    HostApiVersion,
    ManifestVersion,
    PluginDataSchemaVersion,
    PluginDefinition,
    PluginDescription,
    PluginTitle,
    SecretReferenceSlot,
)
from mymcp.plugin.manifest import (
    PluginContractError,
    PluginContractErrorCode,
    parse_manifest_bytes,
    parse_manifest_mapping,
    validate_plugin_contract,
)

__all__ = [
    "ActivatedTool",
    "AuthorityDeclaration",
    "CapabilityContractVersion",
    "CapabilityDeclaration",
    "CapabilityKind",
    "CapabilityLocalId",
    "ComposedToolSurface",
    "ConfigurationDeclaration",
    "ConfigurationSchema",
    "ConfigurationSchemaVersion",
    "ConfigurationType",
    "ConsentRequirement",
    "FilesystemAuthority",
    "HostToolOrigin",
    "HostApiRange",
    "HostApiVersion",
    "ManifestVersion",
    "PluginDataSchemaVersion",
    "PluginDefinition",
    "PluginDescription",
    "PluginId",
    "PluginContribution",
    "PluginContractError",
    "PluginContractErrorCode",
    "PluginTitle",
    "PluginVersion",
    "PublicToolBinding",
    "QualifiedCapabilityId",
    "SecretReferenceSlot",
    "ToolEffects",
    "compose_tool_surface",
    "parse_manifest_bytes",
    "parse_manifest_mapping",
    "validate_plugin_contract",
]
